/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/router/__root'
import { Route as SetupPasswordRouteImport } from './app/router/setup-password'
import { Route as AuthenticatedRouteImport } from './app/router/_authenticated'
import { Route as IndexRouteImport } from './app/router/index'
import { Route as AuthenticatedUsersRouteImport } from './app/router/_authenticated/users'
import { Route as AuthenticatedTimetablesRouteImport } from './app/router/_authenticated/timetables'
import { Route as AuthenticatedTeacherAssignmentsRouteImport } from './app/router/_authenticated/teacher-assignments'
import { Route as AuthenticatedSubjectsRouteImport } from './app/router/_authenticated/subjects'
import { Route as AuthenticatedStudentsRouteImport } from './app/router/_authenticated/students'
import { Route as AuthenticatedSettingsRouteImport } from './app/router/_authenticated/settings'
import { Route as AuthenticatedRbacRouteImport } from './app/router/_authenticated/rbac'
import { Route as AuthenticatedProfileRouteImport } from './app/router/_authenticated/profile'
import { Route as AuthenticatedPhysicalSpacesRouteImport } from './app/router/_authenticated/physical-spaces'
import { Route as AuthenticatedIdentityRouteImport } from './app/router/_authenticated/identity'
import { Route as AuthenticatedGradesRouteImport } from './app/router/_authenticated/grades'
import { Route as AuthenticatedEnrollmentsRouteImport } from './app/router/_authenticated/enrollments'
import { Route as AuthenticatedDataUpdatesRouteImport } from './app/router/_authenticated/data-updates'
import { Route as AuthenticatedDashboardRouteImport } from './app/router/_authenticated/dashboard'
import { Route as AuthenticatedClassroomsRouteImport } from './app/router/_authenticated/classrooms'
import { Route as AuthenticatedAuditRouteImport } from './app/router/_authenticated/audit'
import { Route as AuthenticatedAttendanceRouteImport } from './app/router/_authenticated/attendance'
import { Route as AuthenticatedAcademicYearsRouteImport } from './app/router/_authenticated/academic-years'
import { Route as AuthenticatedStudentsIndexRouteImport } from './app/router/_authenticated/students.index'
import { Route as AuthenticatedEnrollmentsIndexRouteImport } from './app/router/_authenticated/enrollments.index'
import { Route as AuthenticatedStudentsImportRouteImport } from './app/router/_authenticated/students.import'
import { Route as AuthenticatedEnrollmentsNewRouteImport } from './app/router/_authenticated/enrollments.new'

const SetupPasswordRoute = SetupPasswordRouteImport.update({
  id: '/setup-password',
  path: '/setup-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./app/router/_authenticated/users.lazy').then((d) => d.Route),
)
const AuthenticatedTimetablesRoute = AuthenticatedTimetablesRouteImport.update({
  id: '/timetables',
  path: '/timetables',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./app/router/_authenticated/timetables.lazy').then((d) => d.Route),
)
const AuthenticatedTeacherAssignmentsRoute =
  AuthenticatedTeacherAssignmentsRouteImport.update({
    id: '/teacher-assignments',
    path: '/teacher-assignments',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./app/router/_authenticated/teacher-assignments.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedSubjectsRoute = AuthenticatedSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./app/router/_authenticated/subjects.lazy').then((d) => d.Route),
)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./app/router/_authenticated/settings.lazy').then((d) => d.Route),
)
const AuthenticatedRbacRoute = AuthenticatedRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./app/router/_authenticated/rbac.lazy').then((d) => d.Route),
)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./app/router/_authenticated/profile.lazy').then((d) => d.Route),
)
const AuthenticatedPhysicalSpacesRoute =
  AuthenticatedPhysicalSpacesRouteImport.update({
    id: '/physical-spaces',
    path: '/physical-spaces',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./app/router/_authenticated/physical-spaces.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedIdentityRoute = AuthenticatedIdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./app/router/_authenticated/identity.lazy').then((d) => d.Route),
)
const AuthenticatedGradesRoute = AuthenticatedGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./app/router/_authenticated/grades.lazy').then((d) => d.Route),
)
const AuthenticatedEnrollmentsRoute =
  AuthenticatedEnrollmentsRouteImport.update({
    id: '/enrollments',
    path: '/enrollments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDataUpdatesRoute =
  AuthenticatedDataUpdatesRouteImport.update({
    id: '/data-updates',
    path: '/data-updates',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./app/router/_authenticated/data-updates.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./app/router/_authenticated/dashboard.lazy').then((d) => d.Route),
)
const AuthenticatedClassroomsRoute = AuthenticatedClassroomsRouteImport.update({
  id: '/classrooms',
  path: '/classrooms',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./app/router/_authenticated/classrooms.lazy').then((d) => d.Route),
)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./app/router/_authenticated/audit.lazy').then((d) => d.Route),
)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./app/router/_authenticated/attendance.lazy').then((d) => d.Route),
)
const AuthenticatedAcademicYearsRoute =
  AuthenticatedAcademicYearsRouteImport.update({
    id: '/academic-years',
    path: '/academic-years',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./app/router/_authenticated/academic-years.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any).lazy(() =>
    import('./app/router/_authenticated/students.index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedEnrollmentsIndexRoute =
  AuthenticatedEnrollmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEnrollmentsRoute,
  } as any).lazy(() =>
    import('./app/router/_authenticated/enrollments.index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedStudentsImportRoute =
  AuthenticatedStudentsImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any).lazy(() =>
    import('./app/router/_authenticated/students.import.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedEnrollmentsNewRoute =
  AuthenticatedEnrollmentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedEnrollmentsRoute,
  } as any).lazy(() =>
    import('./app/router/_authenticated/enrollments.new.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setup-password': typeof SetupPasswordRoute
  '/academic-years': typeof AuthenticatedAcademicYearsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/classrooms': typeof AuthenticatedClassroomsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-updates': typeof AuthenticatedDataUpdatesRoute
  '/enrollments': typeof AuthenticatedEnrollmentsRouteWithChildren
  '/grades': typeof AuthenticatedGradesRoute
  '/identity': typeof AuthenticatedIdentityRoute
  '/physical-spaces': typeof AuthenticatedPhysicalSpacesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rbac': typeof AuthenticatedRbacRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/subjects': typeof AuthenticatedSubjectsRoute
  '/teacher-assignments': typeof AuthenticatedTeacherAssignmentsRoute
  '/timetables': typeof AuthenticatedTimetablesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/enrollments/new': typeof AuthenticatedEnrollmentsNewRoute
  '/students/import': typeof AuthenticatedStudentsImportRoute
  '/enrollments/': typeof AuthenticatedEnrollmentsIndexRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup-password': typeof SetupPasswordRoute
  '/academic-years': typeof AuthenticatedAcademicYearsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/classrooms': typeof AuthenticatedClassroomsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-updates': typeof AuthenticatedDataUpdatesRoute
  '/grades': typeof AuthenticatedGradesRoute
  '/identity': typeof AuthenticatedIdentityRoute
  '/physical-spaces': typeof AuthenticatedPhysicalSpacesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rbac': typeof AuthenticatedRbacRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subjects': typeof AuthenticatedSubjectsRoute
  '/teacher-assignments': typeof AuthenticatedTeacherAssignmentsRoute
  '/timetables': typeof AuthenticatedTimetablesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/enrollments/new': typeof AuthenticatedEnrollmentsNewRoute
  '/students/import': typeof AuthenticatedStudentsImportRoute
  '/enrollments': typeof AuthenticatedEnrollmentsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/setup-password': typeof SetupPasswordRoute
  '/_authenticated/academic-years': typeof AuthenticatedAcademicYearsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/classrooms': typeof AuthenticatedClassroomsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/data-updates': typeof AuthenticatedDataUpdatesRoute
  '/_authenticated/enrollments': typeof AuthenticatedEnrollmentsRouteWithChildren
  '/_authenticated/grades': typeof AuthenticatedGradesRoute
  '/_authenticated/identity': typeof AuthenticatedIdentityRoute
  '/_authenticated/physical-spaces': typeof AuthenticatedPhysicalSpacesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/rbac': typeof AuthenticatedRbacRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/_authenticated/subjects': typeof AuthenticatedSubjectsRoute
  '/_authenticated/teacher-assignments': typeof AuthenticatedTeacherAssignmentsRoute
  '/_authenticated/timetables': typeof AuthenticatedTimetablesRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/enrollments/new': typeof AuthenticatedEnrollmentsNewRoute
  '/_authenticated/students/import': typeof AuthenticatedStudentsImportRoute
  '/_authenticated/enrollments/': typeof AuthenticatedEnrollmentsIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup-password'
    | '/academic-years'
    | '/attendance'
    | '/audit'
    | '/classrooms'
    | '/dashboard'
    | '/data-updates'
    | '/enrollments'
    | '/grades'
    | '/identity'
    | '/physical-spaces'
    | '/profile'
    | '/rbac'
    | '/settings'
    | '/students'
    | '/subjects'
    | '/teacher-assignments'
    | '/timetables'
    | '/users'
    | '/enrollments/new'
    | '/students/import'
    | '/enrollments/'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup-password'
    | '/academic-years'
    | '/attendance'
    | '/audit'
    | '/classrooms'
    | '/dashboard'
    | '/data-updates'
    | '/grades'
    | '/identity'
    | '/physical-spaces'
    | '/profile'
    | '/rbac'
    | '/settings'
    | '/subjects'
    | '/teacher-assignments'
    | '/timetables'
    | '/users'
    | '/enrollments/new'
    | '/students/import'
    | '/enrollments'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/setup-password'
    | '/_authenticated/academic-years'
    | '/_authenticated/attendance'
    | '/_authenticated/audit'
    | '/_authenticated/classrooms'
    | '/_authenticated/dashboard'
    | '/_authenticated/data-updates'
    | '/_authenticated/enrollments'
    | '/_authenticated/grades'
    | '/_authenticated/identity'
    | '/_authenticated/physical-spaces'
    | '/_authenticated/profile'
    | '/_authenticated/rbac'
    | '/_authenticated/settings'
    | '/_authenticated/students'
    | '/_authenticated/subjects'
    | '/_authenticated/teacher-assignments'
    | '/_authenticated/timetables'
    | '/_authenticated/users'
    | '/_authenticated/enrollments/new'
    | '/_authenticated/students/import'
    | '/_authenticated/enrollments/'
    | '/_authenticated/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SetupPasswordRoute: typeof SetupPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup-password': {
      id: '/setup-password'
      path: '/setup-password'
      fullPath: '/setup-password'
      preLoaderRoute: typeof SetupPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/timetables': {
      id: '/_authenticated/timetables'
      path: '/timetables'
      fullPath: '/timetables'
      preLoaderRoute: typeof AuthenticatedTimetablesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher-assignments': {
      id: '/_authenticated/teacher-assignments'
      path: '/teacher-assignments'
      fullPath: '/teacher-assignments'
      preLoaderRoute: typeof AuthenticatedTeacherAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subjects': {
      id: '/_authenticated/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AuthenticatedSubjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rbac': {
      id: '/_authenticated/rbac'
      path: '/rbac'
      fullPath: '/rbac'
      preLoaderRoute: typeof AuthenticatedRbacRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/physical-spaces': {
      id: '/_authenticated/physical-spaces'
      path: '/physical-spaces'
      fullPath: '/physical-spaces'
      preLoaderRoute: typeof AuthenticatedPhysicalSpacesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/identity': {
      id: '/_authenticated/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof AuthenticatedIdentityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grades': {
      id: '/_authenticated/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AuthenticatedGradesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/enrollments': {
      id: '/_authenticated/enrollments'
      path: '/enrollments'
      fullPath: '/enrollments'
      preLoaderRoute: typeof AuthenticatedEnrollmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data-updates': {
      id: '/_authenticated/data-updates'
      path: '/data-updates'
      fullPath: '/data-updates'
      preLoaderRoute: typeof AuthenticatedDataUpdatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classrooms': {
      id: '/_authenticated/classrooms'
      path: '/classrooms'
      fullPath: '/classrooms'
      preLoaderRoute: typeof AuthenticatedClassroomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/academic-years': {
      id: '/_authenticated/academic-years'
      path: '/academic-years'
      fullPath: '/academic-years'
      preLoaderRoute: typeof AuthenticatedAcademicYearsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/enrollments/': {
      id: '/_authenticated/enrollments/'
      path: '/'
      fullPath: '/enrollments/'
      preLoaderRoute: typeof AuthenticatedEnrollmentsIndexRouteImport
      parentRoute: typeof AuthenticatedEnrollmentsRoute
    }
    '/_authenticated/students/import': {
      id: '/_authenticated/students/import'
      path: '/import'
      fullPath: '/students/import'
      preLoaderRoute: typeof AuthenticatedStudentsImportRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/enrollments/new': {
      id: '/_authenticated/enrollments/new'
      path: '/new'
      fullPath: '/enrollments/new'
      preLoaderRoute: typeof AuthenticatedEnrollmentsNewRouteImport
      parentRoute: typeof AuthenticatedEnrollmentsRoute
    }
  }
}

interface AuthenticatedEnrollmentsRouteChildren {
  AuthenticatedEnrollmentsNewRoute: typeof AuthenticatedEnrollmentsNewRoute
  AuthenticatedEnrollmentsIndexRoute: typeof AuthenticatedEnrollmentsIndexRoute
}

const AuthenticatedEnrollmentsRouteChildren: AuthenticatedEnrollmentsRouteChildren =
  {
    AuthenticatedEnrollmentsNewRoute: AuthenticatedEnrollmentsNewRoute,
    AuthenticatedEnrollmentsIndexRoute: AuthenticatedEnrollmentsIndexRoute,
  }

const AuthenticatedEnrollmentsRouteWithChildren =
  AuthenticatedEnrollmentsRoute._addFileChildren(
    AuthenticatedEnrollmentsRouteChildren,
  )

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsImportRoute: typeof AuthenticatedStudentsImportRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsImportRoute: AuthenticatedStudentsImportRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAcademicYearsRoute: typeof AuthenticatedAcademicYearsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedClassroomsRoute: typeof AuthenticatedClassroomsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDataUpdatesRoute: typeof AuthenticatedDataUpdatesRoute
  AuthenticatedEnrollmentsRoute: typeof AuthenticatedEnrollmentsRouteWithChildren
  AuthenticatedGradesRoute: typeof AuthenticatedGradesRoute
  AuthenticatedIdentityRoute: typeof AuthenticatedIdentityRoute
  AuthenticatedPhysicalSpacesRoute: typeof AuthenticatedPhysicalSpacesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRbacRoute: typeof AuthenticatedRbacRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
  AuthenticatedSubjectsRoute: typeof AuthenticatedSubjectsRoute
  AuthenticatedTeacherAssignmentsRoute: typeof AuthenticatedTeacherAssignmentsRoute
  AuthenticatedTimetablesRoute: typeof AuthenticatedTimetablesRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAcademicYearsRoute: AuthenticatedAcademicYearsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedClassroomsRoute: AuthenticatedClassroomsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDataUpdatesRoute: AuthenticatedDataUpdatesRoute,
  AuthenticatedEnrollmentsRoute: AuthenticatedEnrollmentsRouteWithChildren,
  AuthenticatedGradesRoute: AuthenticatedGradesRoute,
  AuthenticatedIdentityRoute: AuthenticatedIdentityRoute,
  AuthenticatedPhysicalSpacesRoute: AuthenticatedPhysicalSpacesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRbacRoute: AuthenticatedRbacRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
  AuthenticatedSubjectsRoute: AuthenticatedSubjectsRoute,
  AuthenticatedTeacherAssignmentsRoute: AuthenticatedTeacherAssignmentsRoute,
  AuthenticatedTimetablesRoute: AuthenticatedTimetablesRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SetupPasswordRoute: SetupPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
