export { default as AcademicYearDrawer } from './components/academic-year-drawer'
export { default as TrimestersDrawer } from './components/trimesters-drawer'
export * from './components/academic-years-ui'
export { default as AcademicYearsPage } from './components/academic-years-page'
export { TourOrchestrator } from './components/tour-orchestrator'
export { AcademicYearsService } from './api/academic-years.service'

export { useAcademicYearsData, useAcademicYearReadiness } from './hooks/use-academic-years-data'
export { useAcademicYearsDrawers } from './hooks/use-academic-years-drawers'
export { useTrimestersData } from './hooks/use-trimesters-data'
export { useTourStore } from './store/use-tour-store'
export { DIRECTOR_TOUR_STEPS } from './constants/tour-steps'

export * from './types/academic-years.types'
export { academicYearFormSchema } from './schemas/academic-years.schema'
export type { AcademicYearFormValues } from './schemas/academic-years.schema'
